############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "Teams"
pageRef = "/teams"
weight = 3

[[main]]
name = "Charter Standard"
pageRef = "/charterstandard"
weight = 4

[[main]]
name = "RESPECT"
pageRef = "/respect"
weight = 5

[[main]]
name = "Club Information"
pageRef = "/clubinfo"
weight = 6

[[main]]
name = "Sponsors"
pageRef = "/sponsors"
weight = 7

[[main]]
name = "Elements"
pageRef = "/elements"
weight = 8

[[main]]
weight = 9
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
